apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "piston.fullname" . }}-api
  labels:
    app: {{ include "piston.name" . }}
    component: api
spec:
  replicas: {{ .Values.replicaCountApi }}
  selector:
    matchLabels:
      app: {{ include "piston.name" . }}
      component: api
  template:
    metadata:
      labels:
        app: {{ include "piston.name" . }}
        component: api
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repositoryApi }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.api.targetPort }}
          resources:
{{ toYaml .Values.resources.api | indent 12 }}
          volumeMounts:
            - name: packages
              mountPath: /piston/packages
      volumes:
        - name: packages
          persistentVolumeClaim:
            claimName: {{ include "piston.fullname" . }}-api-pvc
