apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "piston.fullname" . }}-repo
  labels:
    app: {{ include "piston.name" . }}
    component: repo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "piston.name" . }}
      component: repo
  template:
    metadata:
      labels:
        app: {{ include "piston.name" . }}
        component: repo
    spec:
      hostPID: {{ .Values.security.hostPID }}
{{- if .Values.repo.gitUrl }}
      initContainers:
        - name: checkout
          image: alpine/git
          command:
            - sh
            - -c
            - |
              set -e
              rm -rf /piston/* /piston/.* 2>/dev/null || true
              git clone {{ .Values.repo.gitUrl }} /piston
              {{- if .Values.repo.gitBranch }}
              cd /piston && git checkout {{ .Values.repo.gitBranch }}
              {{- end }}
          volumeMounts:
            - name: piston-data
              mountPath: /piston
{{- end }}
      containers:
        - name: repo
          securityContext:
            privileged: {{ .Values.security.privileged }}
          image: "{{ .Values.image.repositoryRepo }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.repo.targetPort }}
          env:
{{- if .Values.env.repo }}
{{- range $name, $value := .Values.env.repo }}
            - name: {{ $name }}
              value: "{{ $value }}"
{{- end }}
{{- end }}
          resources:
{{ toYaml .Values.resources.repo | indent 12 }}
          volumeMounts:
            - name: piston-data
              mountPath: /piston
            - name: cgroup
              mountPath: /sys/fs/cgroup
              readOnly: false
{{- if .Values.docker.enableSocket }}
            - name: dockersock
              mountPath: {{ .Values.docker.socketPath }}
{{- end }}
{{- if .Values.docker.enableDinD }}
            - name: dind-socket
              mountPath: /var/run
{{- end }}
{{- if .Values.docker.enableDinD }}
        - name: docker-dind
          image: "{{ .Values.docker.dindImage }}"
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: {{ .Values.docker.privilegedDinD }}
          volumeMounts:
            - name: dind-socket
              mountPath: /var/run
{{- end }}
      volumes:
        - name: piston-data
          persistentVolumeClaim:
            claimName: {{ include "piston.fullname" . }}-repo-pvc
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
            type: Directory
{{- if .Values.docker.enableSocket }}
        - name: dockersock
          hostPath:
            path: {{ .Values.docker.socketPath }}
            type: Socket
{{- end }}
{{- if .Values.docker.enableDinD }}
        - name: dind-socket
          emptyDir: {}
{{- end }}
