apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "piston.fullname" . }}-repo-pvc
  labels:
    app: {{ include "piston.name" . }}
    component: repo
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.sizeRepo }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
