apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "piston.fullname" . }}-api-pvc
  labels:
    app: {{ include "piston.name" . }}
    component: api
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.sizeApi }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
