apiVersion: v1
kind: Service
metadata:
  name: {{ include "piston.fullname" . }}-api
  labels:
    app: {{ include "piston.name" . }}
    component: api
spec:
  type: {{ .Values.service.api.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: {{ .Values.service.api.targetPort }}
  selector:
    app: {{ include "piston.name" . }}
    component: api
